# Generated by Django 4.2.16 on 2026-04-15 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(blank=True, default="", max_length=64)),
                ("username", models.CharField(blank=True, default="", max_length=64)),
                ("photo_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "language_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
