# Generated by Django 4.2.16 on 2026-04-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_userbudgetlink_budgetinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="total_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sub_budget_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="budget.category",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="budget.budget",
                    ),
                ),
            ],
            options={
                "unique_together": {("budget", "name")},
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="transactions", to="budget.tag"
            ),
        ),
    ]
