# Generated by Django 4.2.16 on 2026-04-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0007_subbudget_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField()),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                ("link", models.URLField(blank=True, default="", max_length=2000)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("image_url", models.URLField(blank=True, default="", max_length=2000)),
                ("is_reserved", models.BooleanField(default=False)),
                ("reserved_by", models.BigIntegerField(blank=True, null=True)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishes",
                        to="budget.budget",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
