# Generated by Django 4.2.16 on 2026-04-28 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0009_wishitem_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishitem",
            name="goal_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="queue_position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wishitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("fulfilled", "Fulfilled"),
                    ("locked", "Locked"),
                    ("done", "Done (goal funded)"),
                    ("pool", "Pool (goal-ready)"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="GoalSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "accumulated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("carried", "Carried forward"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_sessions",
                        to="budget.budget",
                    ),
                ),
                (
                    "wish_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_sessions",
                        to="budget.wishitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SavingsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("daily_surplus", models.DecimalField(decimal_places=2, max_digits=14)),
                ("wish_split_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("wish_credit", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "reserve_credit",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("streak_day", models.IntegerField(default=0)),
                (
                    "multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                ("is_surprise_day", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_events",
                        to="budget.budget",
                    ),
                ),
                (
                    "goal_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_events",
                        to="budget.goalsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("budget", "date")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=7)),
                (
                    "base_split_pct",
                    models.DecimalField(decimal_places=2, default=60, max_digits=5),
                ),
                ("surprise_day", models.IntegerField(blank=True, null=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_configs",
                        to="budget.budget",
                    ),
                ),
            ],
            options={
                "unique_together": {("budget", "month")},
            },
        ),
    ]
